#!/bin/bash

echo "========================================="
echo "🚀 QUICK START - Portfolio Admin"
echo "========================================="
echo ""
echo "Exécutez ces commandes dans le container Laravel:"
echo ""
echo "docker compose exec app bash"
echo ""
echo "Puis:"
echo ""
echo "php artisan storage:link"
echo "php artisan migrate:fresh"
echo "php artisan db:seed --class=AdminSeeder"
echo "npm install && npm run build"
echo ""
echo "========================================="
echo "🔑 Connexion Admin"
echo "========================================="
echo ""
echo "URL: http://localhost:8081/login"
echo "Email: admin@sddavid.com"
echo "Password: Password1234"
echo ""
echo "========================================="
