name: Deploy to VPS

on:
  push:
    branches:
      - main # Exécute le workflow au push sur la branche main
  workflow_dispatch: # Permet de lancer le workflow manuellement depuis GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "1. Aller dans le dossier du projet sur le VPS"
            # Chemin configuré par Ansible
            cd /var/www/MonPortfolio

            echo "2. Récupérer les dernières modifications de GitHub"
            git pull origin main

            echo "3. Lancer le script de déploiement"
            # Donne les droits d'exécution si ce n'est pas fait
            chmod +x run.sh

            # Exécute la fonction de déploiement (build assets + migration + restart)
            ./run.sh deploy
